
version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile.api
    ports: ["8000:8000"]
    env_file:
      - ./configs/.env
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request,sys; urllib.request.urlopen('http://localhost:8000/health'); print('ok')"]
      interval: 15s
      timeout: 5s
      retries: 5
  ui:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile.ui
    ports: ["8501:8501"]
    env_file:
      - ./configs/.env
    depends_on:
      - api
