
[tool.black]
line-length = 100
target-version = ["py310"]

[tool.ruff]
line-length = 100
target-version = "py310"
extend-select = ["I"]
ignore = ["E501"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
